### PR TITLE
Add new features: Timeout, Context Data, Multi pool configuration

### PR DESCRIPTION
**Pull request by 0xGosu**
**New features**
+Add `NAMEKO_TIMEOUT` configuration in setting.py to set a timeout for every RPC
+Add  `NAMEKO_CONTEXT_DATA` configuration in setting.py to set context_data for every RPC
**Bug fixes**
+Fix bug ClusterRPC worker stop working after connection error by remove and insert new worker instance into the ClusterRpcProxyPool
**Other changes**
+Add Jetbrain IDE patterns in`.gitignore` file
+Bump version to 0.2

### CODE REVIEW

**Comment by and3rson** [comment]
Hi! Thank you for your contribution!

Unfortunately I have no time to maintain this repo anymore, so if you wish - I can grant you write access here as well as to the PyPi package. Of course, only if you want :)

**Comment by 0xGosu** [comment]
Thank you, if so then pls. I'm currently using this library for most of my current works. Will contribute to this repo a lot more if I have your permission.

**Review by and3rson — APPROVED** [review]

**Comment by and3rson** [comment]
Thanks! Those changes look great.
P. S. I've sent you an invitation to join this repo to gain push access.

**Comment by 0xGosu** [comment]
**New features:**
+Allow multiple pools to be initialized using different configuration with 'default' pool config as default configuration (all config will be merged)
**Other changes:**
+Bump version to 0.5
**Notes:**
'POOL_SIZE' is equivalent to NAMEKO_POOL_SIZE
'POOL_CONTEXT_DATA' is equivalent to NAMEKO_CONTEXT_DATA
'POOL_TIMEOUT' is equivalent to NAMEKO_TIMEOUT
in the previous release.
Old configuration with a single pool still works as normal. No code changes required
This version setting config is compatible with the config of version 0.1,0.2,0.3 but not 0.4
```
NAMEKO_CONFIG={
    'default': {
        'AMQP_URL': 'amqp://',
        'POOL_SIZE': 4,
        'POOL_CONTEXT_DATA': {"common": "multi"},
        'POOL_TIMEOUT': None
    },
    'pool1': {
        'AMQP_URL': 'amqp://pool2',
        'POOL_CONTEXT_DATA': {"name": "pool1", "data": 123},
    },
    'pool2': {
        'AMQP_URL': 'amqp://pool3',
        'POOL_CONTEXT_DATA': {"name": "pool2", "data": 321},
        'POOL_TIMEOUT': 60
    },
    'pool3': {
        'POOL_SIZE': 8,
        'POOL_TIMEOUT': 60
    }
}```

**Comment by 0xGosu** [comment]
@and3rson can you also give me access to PyPi. Please add my account `tranvietanh1991` as one of the Collaborators

**Comment by and3rson** [comment]
@tranvietanh1991 done. Thank you for maintaining the project!

**Review by and3rson — APPROVED** [review]

**Comment by 0xGosu** [comment]
@and3rson thank you

**Pull request merged**
